[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Tell Netlify to ignore the Supabase anon key in security scan
  # This key is meant to be public
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"